yarnPath: .yarn/releases/yarn-2.4.0.cjs

# added because of this issue: https://github.com/yarnpkg/berry/issues/1427
packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"