# set base image (host OS)
FROM node:14.5.0

# set the working directory in the container
WORKDIR /app

# expose the port
EXPOSE 3000

# run the app
CMD bash -c "yarn install && yarn start-dev-docker"
